/* config.h -- normally generated by autoconf; hand-written for the source fork */
#ifndef DOOM_CONFIG_H
#define DOOM_CONFIG_H

#define PACKAGE_STRING   "Chocolate Doom"
#define PACKAGE_TARNAME  "chocolate-doom"
#define PACKAGE_NAME     "Chocolate Doom"
#define PACKAGE_VERSION  "3.1.0-of"
#define PACKAGE_BUGREPORT "none"
#define PACKAGE          "chocolate-doom"

#define PROGRAM_PREFIX   "chocolate-"

/* No optional deps on our build. */
/* HAVE_FLUIDSYNTH not defined */
/* HAVE_LIBPNG      not defined */
/* HAVE_LIBSAMPLERATE not defined */

#define HAVE_DECL_STRCASECMP  1
#define HAVE_DECL_STRNCASECMP 1
#define HAVE_STDINT_H         1
#define HAVE_INTTYPES_H       1
#define HAVE_DIRENT_H         1
#define HAVE_IOPERM           0

#endif /* DOOM_CONFIG_H */
