/*
 * Quad and fan submission with RSP vertex-slot reuse. See r_tri.h for why
 * this exists and why reordering the triangles is safe.
 */
#include "r_tri.h"

#if defined(N64) && R_TRIFAST && !R_NOTRI

#include <math.h>

/* R_TRI_NEAR comes from r_tri.h now: push-time quantization computes the
 * same depth mapping outside this file. */

/* floorf() is a libm CALL on this toolchain, not an instruction -- the
 * conversion helpers live in r_fastmath.h (native floor.w.s via inline asm,
 * one FPU op) and r_tri.h (r_tri_s16_16, the clamped s16.16), shared with
 * the per-vertex emitters that inline them. R_FASTFLOOR=0 restores the libm
 * calls; there is no output difference to weigh -- identical integers -- so
 * it is a speed switch only. */
#define TRI_DATA_LEN  R_TRI_DATA_LEN
/* VERTEX_ROUND=1 rounds screen positions to the quarter-pixel grid instead
 * of flooring them.
 *
 * Two flats that share a world edge each compute that point through their
 * OWN transform and clip chain -- one side's vertex may be an original
 * polygon corner while the other's is generated by a clip interpolation at
 * the same world position. The floats then differ in their last bits, and
 * floor turns a one-ULP difference into a whole quarter-pixel wherever it
 * straddles a grid boundary. Along a sloped edge that happens
 * periodically, which is a DOTTED run of pixels neither triangle claims.
 *
 * Rounding does not make the two agree, but it moves every boundary by
 * half a step, so if truncation is the mechanism the gaps must move or
 * change character. That is what this is for: it is a diagnostic, not a
 * proposed fix. */
#if defined(R_VERTEX_ROUND) && R_VERTEX_ROUND != 0
/* Signed, in tenths of a quarter-pixel step: +5 biases half a step up,
 * -5 half a step down. Both directions matter -- if the two sides of a
 * shared edge disagree by less than one step, which way the quantiser
 * leans decides which of them claims the boundary pixel, and a systematic
 * bias shows as better one way and worse the other. +5 was tried and made
 * the seam worse, which is why the lever became signed. */
#define tri_floor_i32(f) rf_floor_i32((f) + (float)R_VERTEX_ROUND * 0.1f)
#else
#define tri_floor_i32 rf_floor_i32
#endif
#define f_to_s16_16   r_tri_s16_16

/* Convert one vertex and place it in an RSP slot. The conversion is a
 * transcription of rdpq_triangle_rsp's inner loop -- deliberately, so the
 * two paths produce bit-identical vertex data and can be A/B'd. */
static inline void tri_vertex(const rdpq_trifmt_t *fmt, int slot, const float *v)
{
    const int16_t x = tri_floor_i32(v[fmt->pos_offset + 0] * 4.0f);
    const int16_t y = tri_floor_i32(v[fmt->pos_offset + 1] * 4.0f);

    int16_t z = 0;
    if (fmt->z_offset >= 0)
        z = v[fmt->z_offset] * 0x7FFF;

    int32_t rgba = 0;
    if (fmt->shade_offset >= 0) {
        const uint32_t r = v[fmt->shade_offset + 0] * 255.0f;
        const uint32_t g = v[fmt->shade_offset + 1] * 255.0f;
        const uint32_t b = v[fmt->shade_offset + 2] * 255.0f;
        const uint32_t a = v[fmt->shade_offset + 3] * 255.0f;
        rgba = (int32_t)((r << 24) | (g << 16) | (b << 8) | a);
    }

    int16_t s = 0, t = 0;
    int32_t w = 0, inv_w = 0;
    if (fmt->tex_offset >= 0) {
        s     = v[fmt->tex_offset + 0] * 32.0f;
        t     = v[fmt->tex_offset + 1] * 32.0f;
        w     = f_to_s16_16(1.0f / v[fmt->tex_offset + 2]);
        inv_w = f_to_s16_16(       v[fmt->tex_offset + 2]);
    }

    rspq_write(RDPQ_OVL_ID, RDPQ_CMD_TRIANGLE_DATA,
               TRI_DATA_LEN * slot,
               (x << 16) | (y & 0xFFFF),
               (z << 16),
               rgba,
               (s << 16) | (t & 0xFFFF),
               w,
               inv_w);
}

/* Draw whatever the three slots currently hold. */
static inline void tri_issue(const rdpq_trifmt_t *fmt)
{
    uint32_t cmd_id = RDPQ_CMD_TRI;
    if (fmt->shade_offset >= 0) cmd_id |= 0x4;
    if (fmt->tex_offset   >= 0) cmd_id |= 0x2;
    if (fmt->z_offset     >= 0) cmd_id |= 0x1;

    rspq_write(RDPQ_OVL_ID, RDPQ_CMD_TRIANGLE,
               0xC000 | (cmd_id << 8) |
               (fmt->tex_mipmaps ? (fmt->tex_mipmaps - 1) << 3 : 0) |
               (fmt->tex_tile & 7));
}

/* Cleared by r_tri_group_begin, set once the group's autosync is on
 * record. Only the first primitive after a tile or TMEM change has to go
 * through rdpq_triangle to register it. Exported (r_tri.h) so per-vertex
 * emitters can take the direct slot path themselves. */
int r_tri_group_reg;
#define group_registered r_tri_group_reg

void r_tri_group_begin(void) { group_registered = 0; }

/* One vertex straight from the batch's six floats. Same arithmetic
 * rdpq performs, minus the ten-float layout it would have been copied
 * into and read back out of. */
/* w is 1/iw, passed in rather than computed here: a wall quad's four corners
 * carry only TWO distinct depths (both left corners share iwa, both right
 * corners share iwb -- see the set_vtx calls in r_wall.c), so computing it per
 * vertex did the same 29-cycle div.s twice for nothing. The caller reuses it
 * where the depths compare equal and divides otherwise, so the saving does not
 * depend on that invariant holding. */
static inline void tri_vertex6(const rdpq_trifmt_t *fmt, int slot,
                               const float *v, float w)
{
    const int16_t x = tri_floor_i32(v[0] * 4.0f);
    const int16_t y = tri_floor_i32(v[1] * 4.0f);

    const float iw = v[5];
    float zf = 1.0f - R_TRI_NEAR * iw;
    if (zf < 0.0f) zf = 0.0f;
    const int16_t z = zf * 0x7FFF;

    const uint32_t c = v[2] * 255.0f;
    const int32_t rgba = (int32_t)((c << 24) | (c << 16) | (c << 8) | 255);

    const int16_t s = v[3] * 32.0f;
    const int16_t t = v[4] * 32.0f;

    rspq_write(RDPQ_OVL_ID, RDPQ_CMD_TRIANGLE_DATA,
               TRI_DATA_LEN * slot,
               (x << 16) | (y & 0xFFFF),
               (z << 16),
               rgba,
               (s << 16) | (t & 0xFFFF),
               f_to_s16_16(w),
               f_to_s16_16(iw));
    (void)fmt;
}

void r_tri_quad6(const rdpq_trifmt_t *fmt, const float v[4][6])
{
    if (!group_registered) {
        /* First primitive since the tile changed: through rdpq, so the
         * autosync requirement is recorded for everything that follows.
         * Only the three vertices rdpq_triangle reads are expanded -- v3
         * goes through tri_vertex6 below and never needs the 10-float row. */
        float x[3][10];
        for (int k = 0; k < 3; k++) {
            x[k][0] = v[k][0]; x[k][1] = v[k][1];
            x[k][2] = x[k][3] = x[k][4] = v[k][2];
            x[k][5] = 1.0f;
            x[k][6] = v[k][3]; x[k][7] = v[k][4]; x[k][8] = v[k][5];
            float z = 1.0f - R_TRI_NEAR * v[k][5];
            x[k][9] = z < 0.0f ? 0.0f : z;
        }
        rdpq_triangle(fmt, x[0], x[1], x[2]);
        group_registered = 1;
        tri_vertex6(fmt, 1, v[3], 1.0f / v[3][5]);
        tri_issue(fmt);
        return;
    }

    /* Two divides, not four: v[3] shares v[0]'s depth and v[2] shares v[1]'s
     * on every wall quad. The equality test is a c.eq.s (~3 cycles) guarding a
     * div.s (~29), so it wins even in the case it is protecting against. */
    const float w0 = 1.0f / v[0][5];
    const float w1 = 1.0f / v[1][5];
    tri_vertex6(fmt, 0, v[0], w0);
    tri_vertex6(fmt, 1, v[1], w1);
    tri_vertex6(fmt, 2, v[2], (v[2][5] == v[1][5]) ? w1 : 1.0f / v[2][5]);
    tri_issue(fmt);
    tri_vertex6(fmt, 1, v[3], (v[3][5] == v[0][5]) ? w0 : 1.0f / v[3][5]);
    tri_issue(fmt);
}

/* Tinted variant of tri_vertex6: the scalar shade multiplies three channel
 * factors (0..255 scale) instead of replicating. shade <= 1 keeps every
 * product inside a byte, so no clamps. */
static inline void tri_vertex6t(const rdpq_trifmt_t *fmt, int slot,
                                const float *v, float w,
                                float tr, float tg, float tb)
{
    const int16_t x = tri_floor_i32(v[0] * 4.0f);
    const int16_t y = tri_floor_i32(v[1] * 4.0f);

    const float iw = v[5];
    float zf = 1.0f - R_TRI_NEAR * iw;
    if (zf < 0.0f) zf = 0.0f;
    const int16_t z = zf * 0x7FFF;

    const uint32_t r = (uint32_t)(v[2] * tr);
    const uint32_t g = (uint32_t)(v[2] * tg);
    const uint32_t b = (uint32_t)(v[2] * tb);
    const int32_t rgba = (int32_t)((r << 24) | (g << 16) | (b << 8) | 255u);

    const int16_t s = v[3] * 32.0f;
    const int16_t t = v[4] * 32.0f;

    rspq_write(RDPQ_OVL_ID, RDPQ_CMD_TRIANGLE_DATA,
               TRI_DATA_LEN * slot,
               (x << 16) | (y & 0xFFFF),
               (z << 16),
               rgba,
               (s << 16) | (t & 0xFFFF),
               f_to_s16_16(w),
               f_to_s16_16(iw));
    (void)fmt;
}

void r_tri_quad6t(const rdpq_trifmt_t *fmt, const float v[4][6],
                  uint32_t tint)
{
    /* 0..255-scale channel factors for the byte path; 0..1 for the
     * registration expansion, whose rdpq conversion multiplies by 255
     * itself. The two round within 1 LSB of each other -- the same class
     * the group-leading/following split already carries. */
    const float tr  = (float)((tint >> 16) & 0xFF);
    const float tg  = (float)((tint >> 8) & 0xFF);
    const float tb  = (float)(tint & 0xFF);

    if (!group_registered) {
        const float trf = tr * (1.0f / 255.0f);
        const float tgf = tg * (1.0f / 255.0f);
        const float tbf = tb * (1.0f / 255.0f);
        float x[3][10];
        for (int k = 0; k < 3; k++) {
            x[k][0] = v[k][0]; x[k][1] = v[k][1];
            x[k][2] = v[k][2] * trf;
            x[k][3] = v[k][2] * tgf;
            x[k][4] = v[k][2] * tbf;
            x[k][5] = 1.0f;
            x[k][6] = v[k][3]; x[k][7] = v[k][4]; x[k][8] = v[k][5];
            float z = 1.0f - R_TRI_NEAR * v[k][5];
            x[k][9] = z < 0.0f ? 0.0f : z;
        }
        rdpq_triangle(fmt, x[0], x[1], x[2]);
        group_registered = 1;
        tri_vertex6t(fmt, 1, v[3], 1.0f / v[3][5], tr, tg, tb);
        tri_issue(fmt);
        return;
    }

    const float w0 = 1.0f / v[0][5];
    const float w1 = 1.0f / v[1][5];
    tri_vertex6t(fmt, 0, v[0], w0, tr, tg, tb);
    tri_vertex6t(fmt, 1, v[1], w1, tr, tg, tb);
    tri_vertex6t(fmt, 2, v[2], (v[2][5] == v[1][5]) ? w1 : 1.0f / v[2][5],
                 tr, tg, tb);
    tri_issue(fmt);
    tri_vertex6t(fmt, 1, v[3], (v[3][5] == v[0][5]) ? w0 : 1.0f / v[3][5],
                 tr, tg, tb);
    tri_issue(fmt);
}

void r_tri_quad(const rdpq_trifmt_t *fmt, const float *v0, const float *v1,
                const float *v2, const float *v3)
{
    /* First triangle through rdpq: it records the autosync requirements and
     * fills slots 0,1,2 with v0,v1,v2. */
    rdpq_triangle(fmt, v0, v1, v2);

    /* Second triangle is {v0,v2,v3}. v0 is already in slot 0 and v2 in
     * slot 2, so only v3 has to be sent -- into slot 1, which makes the
     * slots read {v0,v3,v2}: the same triangle wound the other way, which
     * the RSP resolves when it sorts. */
    tri_vertex(fmt, 1, v3);
    tri_issue(fmt);
}

void r_tri_fan(const rdpq_trifmt_t *fmt, const float (*sv)[10], int m)
{
    if (m < 3) return;

    if (!group_registered) {
        rdpq_triangle(fmt, sv[0], sv[1], sv[2]);
        group_registered = 1;
    } else {
        tri_vertex(fmt, 0, sv[0]);
        tri_vertex(fmt, 1, sv[1]);
        tri_vertex(fmt, 2, sv[2]);
        tri_issue(fmt);
    }

    /* sv[0] stays in slot 0 for the whole fan. Each further triangle shares
     * its previous neighbour, so it needs one new vertex, alternating into
     * the slot the triangle before last used:
     *
     *   slots after start : [v0 v1 v2]
     *   i=3 -> slot1=v3   : [v0 v3 v2]  = {v0,v2,v3}
     *   i=4 -> slot2=v4   : [v0 v3 v4]  = {v0,v3,v4}
     *   i=5 -> slot1=v5   : [v0 v5 v4]  = {v0,v4,v5}
     */
    for (int i = 3; i < m; i++) {
        tri_vertex(fmt, (i & 1) ? 1 : 2, sv[i]);
        tri_issue(fmt);
    }
}

#endif /* N64 && R_TRIFAST && !R_NOTRI */

#if D_TRIBENCH
/* Submit `iters` textured/shaded/z quads through either path and return the
 * elapsed microseconds. Vertices vary per iteration so nothing can be
 * hoisted or cached away; the caller scissors the output to one pixel. */
uint32_t r_tri_bench(int iters, int fast)
{
    static const rdpq_trifmt_t FMT = {
        .pos_offset = 0, .shade_offset = 2, .tex_offset = 6,
        .tex_tile = TILE0, .z_offset = 9,
    };
    float v[4][10];
    if (fast == 2) r_tri_group_begin();
    const uint32_t t0 = TICKS_READ();

    for (int i = 0; i < iters; i++) {
        const float o = (float)(i & 31);
        for (int k = 0; k < 4; k++) {
            v[k][0] = o + (k == 1 || k == 2 ? 16.0f : 0.0f);
            v[k][1] = o + (k >= 2 ? 16.0f : 0.0f);
            v[k][2] = v[k][3] = v[k][4] = 0.75f;
            v[k][5] = 1.0f;
            v[k][6] = (k == 1 || k == 2) ? 16.0f : 0.0f;
            v[k][7] = (k >= 2) ? 16.0f : 0.0f;
            v[k][8] = 1.0f / (32.0f + o);
            v[k][9] = 0.5f;
        }
        if (fast == 2) {
            /* Compact submission: the batch's own six floats, no expansion,
             * and no rdpq call once the group's autosync is registered. */
            float c[4][6];
            for (int k = 0; k < 4; k++) {
                c[k][0] = v[k][0]; c[k][1] = v[k][1]; c[k][2] = v[k][2];
                c[k][3] = v[k][6]; c[k][4] = v[k][7]; c[k][5] = v[k][8];
            }
            r_tri_quad6(&FMT, (const float (*)[6])c);
        } else if (fast) {
            r_tri_quad(&FMT, v[0], v[1], v[2], v[3]);
        } else {
            rdpq_triangle(&FMT, v[0], v[1], v[2]);
            rdpq_triangle(&FMT, v[0], v[2], v[3]);
        }
    }
    return TICKS_TO_US(TICKS_SINCE(t0));
}
#endif
